AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.5.3

Rails:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
