version: '3'

services:
  app:
    container_name: nmax
    image: ruby:2.5.3
    environment:
      PATH: "./bin:$PATH"
    volumes:
      - ./:/nmax
      - bundler-data:/usr/local/bundle
    working_dir: /nmax
    command: /bin/sh -c "while true; do sleep 30; done"

volumes:
  bundler-data:
